if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/codec_interface_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/codec_interface_test[1]_tests.cmake")
else()
  add_test(codec_interface_test_NOT_BUILT codec_interface_test_NOT_BUILT)
endif()
