if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/diagnostics_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/diagnostics_test[1]_tests.cmake")
else()
  add_test(diagnostics_test_NOT_BUILT diagnostics_test_NOT_BUILT)
endif()
