if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/EmitterBoolean_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/EmitterBoolean_test[1]_tests.cmake")
else()
  add_test(EmitterBoolean_test_NOT_BUILT EmitterBoolean_test_NOT_BUILT)
endif()
