if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/parser_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/parser_test[1]_tests.cmake")
else()
  add_test(parser_test_NOT_BUILT parser_test_NOT_BUILT)
endif()
