if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/smoke_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/smoke_test[1]_tests.cmake")
else()
  add_test(smoke_test_NOT_BUILT smoke_test_NOT_BUILT)
endif()
