if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/tag_mapping_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/tag_mapping_test[1]_tests.cmake")
else()
  add_test(tag_mapping_test_NOT_BUILT tag_mapping_test_NOT_BUILT)
endif()
