if(EXISTS "/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/traits_test[1]_tests.cmake")
  include("/Users/andreyshchekin/Documents/projects/aschokin/asn1pp/build5/test/traits_test[1]_tests.cmake")
else()
  add_test(traits_test_NOT_BUILT traits_test_NOT_BUILT)
endif()
