version: "3.8"

services:
  builder:
    build:
      context: ..
      dockerfile: docker/builder/Dockerfile
    volumes:
      - artifacts:/artifacts

  measurer:
    build:
      context: ./measurer
      dockerfile: Dockerfile
    volumes:
      - artifacts:/artifacts
    depends_on:
      builder:
        condition: service_completed_successfully
    environment:
      - ARTIFACTS_DIR=/artifacts

volumes:
  artifacts:
